### ISSUE TITLE
DOI not working

### ISSUE THREAD

**Issue by drisso** [waldronlab/SingleCellMultiModal#12]
Hi Marcel and all,

not sure this is the right place to report this, but the DOI that I see on the landing page of the Bioconductor package does not seem to work: https://doi.org/doi:10.18129/B9.bioc.SingleCellMultiModal

Best,
Davide

**Comment by LiNk-NY** [comment]
Thanks Davide. Sorry for the late reply. I just saw this. Please tag me so I get notified. 
I've asked @lshep. Perhaps @seandavi can chime in?

**Comment by LiNk-NY** [comment]
This has been fixed. Thanks @mtmorgan
