### ISSUE TITLE
Vignette links are 'not found'

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/SingleCellMultiModal#13]
@LiNk-NY 

When I run `browseVignettes("SingleCellMultiModal")`, the vignette page is shows: 

- scNMT Mouse Gastrulation - HTML  source  R code 

But, the HTML, source and R code pages are not.

**Comment by LiNk-NY** [comment]
Hi Kelly, @kbeckenrode 
Are you using RStudio? If so, you should be able to click on the HTML link. 
* If you are using RStudio within Docker, you'd have to use something like
```r
help(package = "SingleCellMultiModal")
```

**Comment by kbeckenrode** [comment]
I am using RStudio on our server. And the HTML did not work. But `help` worked--thank you.

**Comment by LiNk-NY** [comment]
Yes, RStudio is run within a Docker instance. 
Best,
Marcel
