### ISSUE TITLE
Contribution: incorrect link to Google Sheet

### ISSUE THREAD

**Issue by cvanderaa** [waldronlab/SingleCellMultiModal#25]
Hello, 
This is a minor issue. I'm having a look at the contribution guidelines as I would like to add a new dataset, but I see the link to the spreadsheet with available datasets is no pointing to a Google Sheet. I'm referring to this line: https://github.com/waldronlab/SingleCellMultiModal/blob/a839fb62ea74240356681ea39cd6136856933a6f/inst/scripts/Contributing-Guidelines.Rmd#L28

**Comment by kbeckenrode** [comment]
Hi there Chris!

I have updated the URL. Thank you! :)

**Comment by cvanderaa** [comment]
Thanks!

**Comment by LiNk-NY** [comment]
Thanks all!
