### ISSUE TITLE
clean up ECCITEseq vignette output

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/SingleCellMultiModal#32]
Is currently printing many pages of sequences

**Comment by drighelli** [comment]
Yes thanks for pointing me this Levi, this has already been addressed in my yesterday PR 
https://github.com/waldronlab/SingleCellMultiModal/pull/33

**Comment by LiNk-NY** [comment]
@drighelli Levi was referring to this: https://bioconductor.org/packages/release/data/experiment/vignettes/SingleCellMultiModal/inst/doc/ECCITEseq.html#26_sgRNAs_CRISPR_pertubation_data
which was fixed here: 24f1c8ff43c84290c6700bbe7dd2e2fd536a4ead

**Comment by drighelli** [comment]
oh thanks!
