### ISSUE TITLE
PBMC vignette should be named as TENxMultiome

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#34]
The PBMC vignette is named as the dataset cellular type, while it should be better to name it as the corresponding technology. 
There are also other datasets into the package with PBMC data and all the other vignettes are named with the technology name.

Thanks

**Comment by LiNk-NY** [comment]
Thanks! I've renamed the file name to match the function `scMultiome` and updated the vignette title to include `10x PBMC`. 409f609
