### ISSUE TITLE
SingleCellMultiModal function fails with G&T dataset

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#36]
when calling the function `SingleCellMultiModal` with G&Tseq available dataset it returns this error:

`SingleCellMultiModal(c("mouse_gastrulation", "pbmc_10x", "cord_blood", "peripheral_blood", "mouse_embryo_8_cell", "macrophage_differentiation", "mouse_visual_cortex"), versions=c("2.0.0", "1.0.0", "1.0.0","1.0.0","1.0.0","1.0.0","2.0.0"))
Error in .filterMap(DataTypes, dry.run, verbose) : 
  'mouse_embryo_8_cell' is not available, see ?SingleCellMultiModal`
  
  Maybe the function needs to be updated.

**Comment by LiNk-NY** [comment]
Resolved here b96ba806aebadfd3bad9fb72613db8916e76e029
