### ISSUE TITLE
pandoc-citeproc: reference Specht2020-jm not found

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/SingleCellMultiModal#48]
Hi Chris, @cvanderaa 
Is the `Specht2020-jm` reference right? I don't see it `inst/REFERENCES.bib`. 
I do see a  @Specht2021-jm reference. Perhaps those are typos?

**Comment by cvanderaa** [comment]
Hi Marcel, @LiNk-NY 

Sorry for my very late reply. Those are indeed typos that I fixed in the PR linked here above. 
Thanks for noticing!
