### ISSUE TITLE
celltype metadata in scMultiome 10x PBMC tutorial 

### ISSUE THREAD

**Issue by akhst7** [waldronlab/SingleCellMultiModal#50]
Hi, 

In the scMultiome 10x PBMC tutorial tutorial section under a heading `Cell Metadata `,  
`celltype: The cell types have been annotated by the 10x Genomics R&D team using gene markers. 
They provide a rough characterisation of the cell type diversity, but
keep in mind that they are not ground truth labels.`

Which file the output of a 10x sample data (see below) set contains this cell type metadata in the output of a 10x sample data set ?

![Screenshot 2023-03-01 at 4 16 24 PM](https://user-images.githubusercontent.com/3075799/222266869-c1fb631a-ad2f-48b8-90b3-69a216e8152c.png)

**Comment by LiNk-NY** [comment]
Good question. Perhaps @aljabadi or @rargelaguet can answer this.

**Comment by drighelli** [comment]
Dear @akhst7,

I'm sorry for the late answer, we looked into that and can now give you an answer.

The annotation was manually curated by a 10x Genomics team and it is not available in Ricard's script nor in the output of `cellranger`.

Generally speaking, AFAIK `cellranger` is not able to assign cell types, so you'll never find this information in its standard output.

By the way, you can find the `celltype` annotations for this specific dataset in the `colData` of the `MultiAssayExperiment` returned by the `scMultiome` function of our `SingleCellMultiModal` package.

I hope this answer could be useful.

Dario
