### ISSUE TITLE
celltype annotations

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#51]
It seems that we have some already annotated datasets, such as: 
```
SCNMT mouse gastrulation: column lineage
10X multiome: column celltype
seqFISH: both RNAseq and seqFISH (column class)
SCOPE2: protein part column celltype
```
on the other hand annotation is missing for:
```
CITE-seq and ECCITE-seq -> self assigned
GNTseq: Ludwig could you please check about the original paper annotations for this data type, we can discuss it in this thread. :)
```

@lgeistlinger

**Comment by lgeistlinger** [comment]
Hi @drighelli - sorry for the delay! I've checked the G&T papers and it seems that there are no cell type labels available for the Mouse embryo dataset. Do you intend to annotate them computationally eg based on their scRNA-seq profile? This might be a bit of a far shot given that this annotation is not provided by the authors.

**Comment by drighelli** [comment]
Thanks @lgeistlinger, I don't think it's a good idea to assign cell labels to the dataset by ourselves, in particular if we want to define a ground truth.

**Comment by drighelli** [comment]
we reported the already existing cell types and annotated the CITEseq dataset with a manual gating.
We also exported two functions for manual gating `getCellGroups` and `addCTlabels`, an example of usage can be seen in the `scripts/CITEseq_celltypes.R` file
