### ISSUE TITLE
create a ontomap 

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#52]
To keep track of the cell types present in every dataset we create a file `inst/extdata/ontomap.tsv` with the following column names `dataset_name	original_column_name	original_cell_name	ontology_ID	ontology_cell_name`

The idea is to create a new branch for these updates and merge it once everything is ok.

Assigning to me and @kbeckenrode

**Comment by cvanderaa** [comment]
Here are the entries for the SCoPE2 data. 

| dataset_name | original_column_name | original_cell_name | ontology_ID | ontology_cell_name |
|--------------------- | ----------------------------------|-----------------------------|-------------------|-------------------------------|
| macrophage_differentiation  | celltype | Macrophage | CL:0000235  | macrophage  |
| macrophage_differentiation  | celltype | Monocyte | CLO:0009465 | U-937 cell |

**Comment by drighelli** [comment]
thanks @cvanderaa !!!

**Comment by drighelli** [comment]
all cell types have been mapped and indicated in the ontomap file
