### ISSUE TITLE
ECCITEseq data missing rownames

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#60]
Hi @LiNk-NY,

I noticed that the ECCITEseq (also known as `CITEseq("peripheral_blood")`) data have missing `rownames` for HTO and ADT assays.

I'm working on this fault, but I'm wondering how do we handle this in the `ExperimentHub`?

Thanks!

**Comment by LiNk-NY** [comment]
Hi Dario, @drighelli 
I think we can just overwrite the data in `ExperimentHub` since the new change does not change the actual data. 
Before doing so, you can test that the actual data is identical in both the old and new assays.

**Comment by drighelli** [comment]
Okay, but what if we subset the data by filtering out some cells?

Do we need to create a version 2.0?

Thanks for the answers!

**Comment by LiNk-NY** [comment]
Then yes, we'd have to have a new version number.

**Comment by drighelli** [comment]
this has been solved in https://github.com/waldronlab/SingleCellMultiModal/pull/61
