### ISSUE TITLE
Ontology IDs

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/SingleCellMultiModal#63]
[`Here are the ontology IDs`](https://docs.google.com/spreadsheets/d/1WY1vH_Tz7kPxhKV5imXaQWwGHcPXhPVp7z3kgay5hwI/edit#gid=1247451513), but it doesn't align with what I currently see in the repo. @LiNk-NY @drighelli

**Comment by shbrief** [comment]
It seems like you sent the pull request from one of your working branches to the master branch within your own cloned repository, so it'll not affect the master branch of this repository. 

Btw, it looks like you closed that pull request without merging, so the master branch of your repository is not updated either.
One more side note, there is a typo - an underscore in 4E of your Google Sheet, which should be "Primitive Streak". Also, I think row 13 mapping will be better with "CD8-Positive T-Lymphocyte (NCIT:C12542)", using the same ontology DB as the related terms.

**Comment by drighelli** [comment]
Thanks @kbeckenrode for the cell ontology.

It isn't alligned because yesterday @LiNk-NY merged the last version of the `ontomap` (based on https://github.com/waldronlab/SingleCellMultiModal/pull/58 discussion) into the `master` branch of the repo.

I'll merge both versions in a new PR.

**Comment by drighelli** [comment]
this has been solved in https://github.com/waldronlab/SingleCellMultiModal/pull/64
