### ISSUE TITLE
CITEseq cell annotation labels

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#66]
on Centeredd Log Ratio transformated data, see [Seurat](https://satijalab.org/seurat/articles/multimodal_vignette.html) 
using supplementary table ## in the stoeckius paper for annotating cell types.
while identifying thresholds populate a dedicated table in the paper indicating population dimensions and thresholds.

**Comment by drighelli** [comment]
new annotation for `cord_blood` is resolved in https://github.com/waldronlab/SingleCellMultiModal/pull/69

@kbeckenrode, once that @LiNk-NY merges the new PR, could you please update the ontomap with the cell ids for the new cell types?

Thanks everyone!

**Comment by LiNk-NY** [comment]
I have merged PR #69.

**Comment by drighelli** [comment]
this has been fully addressed after Kelly's update on the ontomap
