### ISSUE TITLE
CITEseq MAE to SCE conversion improvements

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#68]
the function `.CITEseqMaeToSce` in `CITEseq.R` file has a few issues:

- doesn't return `metadata` for `peripheral_blood` dataset
- doesn't add the new `clr counts` to the `altExps` of `ADTs` for `cord_blood` dataset
- it can be written by thinking in a more general way where each assay of the MAE is a SCE that can be combined as main and `altExps` assays in the new SCE returned object

**Comment by lwaldron** [comment]
Would be good to address this before publication @drighelli

**Comment by drighelli** [comment]
Thanks @lwaldron I'll work on it.

**Comment by drighelli** [comment]
all previous points have been fixed in https://github.com/waldronlab/SingleCellMultiModal/pull/72 PR
