### ISSUE TITLE
Vignettes not building

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/SingleCellMultiModal#70]
See https://github.com/r-universe/waldronlab/actions/runs/5069485118/jobs/9103162194

**Comment by drighelli** [comment]
Thanks @lwaldron for pointing this out!

@LiNk-NY are the new data already in the EH? I think it could be related to that... I'll look into it better tomorrow!

**Comment by LiNk-NY** [comment]
@drighelli 
I don't think they have been added to the database yet. I can take a look at the error.

**Update**: Yup, it looks like resources e.g., `scADT_clrCounts` haven't been added to the DB.

**Comment by lwaldron** [comment]
Reviving this issue.

**Comment by drighelli** [comment]
@LiNk-NY is there any data still missing ?

**Comment by LiNk-NY** [comment]
I've contacted @kayla-morrell for follow up. 
FWIW, I am checking with: 
```r
> query(eh, "scADT_clrCounts")
ExperimentHub with 0 records
# snapshotDate(): 2023-07-03
```

**Comment by LiNk-NY** [comment]
Thanks to Kayla, it has been fixed. 
```r
> query(eh, "scADT_clrCounts")
ExperimentHub with 1 record
# snapshotDate(): 2023-07-05
# names(): EH8305
# package(): SingleCellMultiModal
# $dataprovider: Innovation Lab, New York Genome Center, New York, United States
# $species: Homo sapiens
# $rdataclass: matrix
# $rdatadateadded: 2023-07-05
# $title: scADT_clrCounts
# $description: scADT_clrCounts data specific to the CORD_BLOOD project
# $taxonomyid: 9606
# $genome: NA
# $sourcetype: TXT
# $sourceurl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE100866
# $sourcesize: NA
# $tags: c("GEO", "ReproducibleResearch", "SingleCellData") 
# retrieve record with 'object[["EH8305"]]' 
```

**Comment by LiNk-NY** [comment]
The latest build on GHA looks good https://github.com/waldronlab/SingleCellMultiModal/actions/runs/5467956548/jobs/9954947568 
I'm pushing to upstream and closing this issue. Thanks.
