### ISSUE TITLE
published paper

### ISSUE THREAD

**Issue by drighelli** [waldronlab/SingleCellMultiModal#74]
could it be a good idea to mention the paper in the README and in the DESCRIPTION file?

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011324

**Comment by LiNk-NY** [comment]
Thanks for bringing this up. I added a `CITATION.cff` file and references to the the `README`. I will note the DOI in the `DESCRIPTION` file.

**Comment by drighelli** [comment]
Thanks Marcel @LiNk-NY !
